/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f407xx.h"
#include "rtc.h"
#include "lcd.h"

int main(void){
	uint8_t last_sec = 0xFF;
    RTC_TIME_t time;
    RTC_DATE_t date;

    //Set initial time and date
    time.hrs = 17;
    time.min = 40;
    time.sec = 0;
    time.time_format = TIME_FORMAT_24HRS;

    date.date  = 19;
    date.month = 4;
    date.year  = 26;
    date.day   = SUNDAY;

    if(RTC_Init() != RTC_INIT_OK){
    while(1);  /*LSE failed to start — halt*/
    }

    RTC_SetCurrentTime(&time);
    RTC_SetCurrentDate(&date);

    //Initiate LCD
    LCD_Init();
    //Clear display before sending data
    LCD_ClearDisplay();

    while(1){

        RTC_GetCurrentTime(&time);
        RTC_GetCurrentDate(&date);

        //keep 1 sec refresh
        if(time.sec != last_sec){
        	last_sec = time.sec;

        	LCD_SetCursor(1, 1);
        	char time_buf[16];
        	sprintf(time_buf, "%02d:%02d:%02d", time.hrs, time.min, time.sec);
        	LCD_SendString(time_buf);//display clock

        	LCD_SetCursor(2, 1);
        	char date_buf[16];
        	sprintf(date_buf, "%02d.%02d.%02d", date.date, date.month, date.year);
        	LCD_SendString(date_buf);//display the date at 2nd row
        }
    }
}

