/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f407xx.h"

int main(void){

	uint8_t last_sec = 0xFF;

    RTC_TIME_t time;
    RTC_DATE_t date;

    /* Set initial time and date */
    time.hrs         = 10;
    time.min         = 30;
    time.sec         = 0;
    time.time_format = TIME_FORMAT_24HRS;

    date.date  = 18;
    date.month = 4;
    date.year  = 26;
    date.day   = SATURDAY;

    if(RTC_Init() != RTC_INIT_OK){
        while(1);  /*LSE failed to start — halt*/
    }

    RTC_SetCurrentTime(&time);
    RTC_SetCurrentDate(&date);

    while(1){

        RTC_GetCurrentTime(&time);
        RTC_GetCurrentDate(&date);

        if(time.sec != last_sec){
        	last_sec = time.sec;
        	printf("%02d:%02d:%02d   %02d.%02d.20%02d\r\n",
        			time.hrs, time.min, time.sec,
					date.date, date.month, date.year);

        	for (uint32_t i = 0; i < 400000; i++);
        	}
        }
    }

